package com.endpoint.manager;
import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nibasabin' at '12/28/16 4:11 PM' with Gradle 3.0
 *
 * @author nibasabin, @date 12/28/16 4:11 PM
 */
@XmlRootElement
public class Library implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * 
	 */
	String name; 
	String age;
	Library(){
	
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getAge() {
		return age;
	}
	public void setAge(String age) {
		this.age = age;
	}

}
