package com.endpoint.manager;
import java.io.Serializable;

import javax.xml.bind.annotation.XmlRootElement;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nibasabin' at '12/28/16 4:11 PM' with Gradle 3.0
 *
 * @author nibasabin, @date 12/28/16 4:11 PM
 */
@Controller
public class Library {

@RequestMapping("/library")
public @ResponseBody String libraryMethod(){
	return "mvc works";
}
}
