/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nibasabin' at '12/28/16 4:11 PM' with Gradle 3.0
 *
 * @author nibasabin, @date 12/28/16 4:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
